### PR TITLE
Providing Docker image and documentation

### PR DESCRIPTION
**Pull request by bernardoVale**
Hello guys, first of all, thanks for writing this tool. It's amazing :)

I'm running Mac OS so I couldn't follow the tutorial without using an EL container.

I think others users might benefit from this.

Please let me know what you guys think.

### CODE REVIEW

**Comment by vishvananda** [comment]
This is very interesting. I actually have something similar (but much smaller one) for running without mock
```
FROM golang:1.9-alpine

RUN apk add git make pigz --update
RUN git clone https://github.com/oracle/smith
RUN (cd smith && make)

FROM scratch
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=0 /go/smith/smith /smith
COPY --from=0 /usr/bin/pigz /usr/bin/pigz
COPY --from=0 /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
COPY --from=0 /lib/libz.so.1 /lib/libz.so.1
VOLUME /tmp
VOLUME /write
WORKDIR /write
ENTRYPOINT ["/smith"]
```
I use it via `docker run -it -v $PWD:/write <image>`

I'd like to make one like yours only minimized with smith and put it on dockerhub but I haven't gotten to it yet. Let me try to get to it today. FYI in order to merge contributions it is necessary for you to sign the OCA as mentioned in the readme.

**Comment by bernardoVale** [comment]
Cool, but how do you run this without mock?

I've tried using your Dockerfile, which is better, but I get this error:

```
INFO[0000] Building in /tmp/smith-build-419716019       
INFO[0000] Installing package                           
INFO[0000] Installing package coreutils                 
ERRO[0000] Failed to reset build environment: Error starting /usr/bin/mock -r /etc/mock/default.cfg --clean: fork/exec /usr/bin/mock: no such file or directory 
INFO[0000] Failed to install coreutils: Error starting /usr/bin/mock -r /etc/mock/default.cfg --clean: fork/exec /usr/bin/mock: no such file or directory 
INFO[0000] Removing /tmp/smith-build-419716019   
```

**Comment by vishvananda** [comment]
There are two types of builds. Mock based builds and oci image based builds. You need mock to do mock based builds for sure.

**Comment by vishvananda** [comment]
I added a Dockerfile that makes an image that is a bit smaller and pushed it into the repository. I pushed the resulting image up to dockerhub so you can test it it you want. Note that the optimial invocation is different depending on whether you are building an rpm/yum based microcontainer or a docker/oci based microcontainer:

for rpm/yum you want to cache a couple of directories in volumes to speed up the builds and you must use --privileged:
`docker run -it --rm --privileged -v $PWD:/write -v cache:/var/cache -v mock:/var/lib/mock vishvananda/smith`

for docker/oci, you don't need those options, but it is useful to cache the /tmp directory
`docker run -it --rm -v $PWD:/write -v tmp:/tmp vishvananda/smith`

Try it out and let me know if it works. Then if you'd like to update the documentation bits of your pr I can merge it.

**Comment by vishvananda** [comment]
@bernardoVale I built an even smaller smith container using smith. It is the `latest` tag at https://hub.docker.com/r/vishvananda/smith. The build from the Dockerfile in the repository is the `ol` tag. You can see that it is about 1/3 of the size of the (already minimized) Dockerfile build. Build can  reproduced from here: https://github.com/vishvananda/smith-inception

**Comment by bernardoVale** [comment]
Cool man, you rock! 🆒 

Before we merge the docs. Should we add the alias example for oci based or yum based?

**Comment by vishvananda** [comment]
@bernardoVale I would think a little example of both would be nice.

**Comment by bernardoVale** [comment]
Agreed. Sorry for the delay. Take a look now

**Comment by vishvananda** [comment]
looks good, thanks

**Pull request merged**
